services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tower-ai-backend
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - HOST=0.0.0.0
      - PORT=8000
      - ALLOWED_ORIGINS=["http://localhost:3000","http://frontend:3000"]
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tower-ai-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:8000
        - REACT_APP_WS_URL=ws://localhost:8000/ws
    container_name: tower-ai-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - tower-ai-network

networks:
  tower-ai-network:
    driver: bridge

volumes:
  backend_logs:
    driver: local
